project_id = "pzgtwjbaoptoqwercygw"

[functions.chat]
verify_jwt = false

[functions.get-learner-recommendations]
verify_jwt = false

[functions.get-student-recommendations]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.generate-narration]
verify_jwt = false

[functions.realtime-token]
verify_jwt = false
